[package]
name = "canokey"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
description = "Transport-free CanoKey host protocol library"
publish = false

[dependencies]
canokey-protocol.workspace = true
canokey-compat.workspace = true
canokey-admin.workspace = true
canokey-piv.workspace = true

x509-info = { workspace = true, optional = true }

[features]
x509 = ["dep:x509-info"]
serde = ["x509", "x509-info/serde"]

[dev-dependencies]
serde_json = "1"

[[example]]
name = "inspect_certificate"
required-features = ["serde"]
